package:
  name: pangalactic.vger
  version: "3.0.dev11"

source:
        path: /home/waterbug/gitlab/pangalactic.vger

requirements:
  build:
    - python
    - setuptools

  run:
    - pangalactic.core=3.0.dev11
    - autobahn
    - pyopenssl
    - python >=2.7
    - service_identity
    - twisted
    - zope
    - zope.interface

about:
  # home: https://pangalactic.us
  license: NASA
  # license_file: LICENSE

