package:
  name: pangalactic.vger
  version: "4.3.dev9"

source:
        path: /home/waterbug/clones/pangalactic.vger

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - autobahn
    - openldap
    - pangalactic.core >=4.3.dev9
    - postgresql
    - psycopg2
    # pynacl is needed for autobahn to support cryptosign auth
    - pynacl
    - pyopenssl >=22.1.0
    - python {{PY_VER}}
    - python-ldap
    - scipy
    - twisted

about:
  # home: https://pangalactic.us
  # license: NASA
  # license_file: LICENSE

