# use ubuntu as a base image
FROM ubuntu

# need to explicitly add sudo package (docker ubuntu does not include)
RUN apt-get update \
 && apt-get install -y sudo

# add the app user scred:pangalactic
RUN groupadd --gid 242 crossbar && \
    useradd --gid 242 --uid 242 -d /home/scred -m scred

# add scred to 'sudo' group and sudo group to sudoers
RUN usermod -a -G sudo scred && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# create 'vger_home', which will be bind-mounted at runtime
RUN mkdir -m 0775 /vger_home && chown -R scred:crossbar /vger_home
RUN mkdir -m 0700 /vgerdb && chown -R scred:crossbar /vgerdb

USER scred
WORKDIR /home/scred
# to get a traceback for C crashes ...
ENV PYTHONFAULTHANDLER=1
ENV PGPORT=65432
COPY Miniconda3-latest-Linux-x86_64.sh .
COPY supervisord.conf .
SHELL ["bash", "-c"]
RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p /home/scred/miniconda
ENV PATH="/home/scred/miniconda/bin:$PATH"
# expose the postgresql port
EXPOSE 65432
RUN conda update conda \
 # force installs of python-ldap and psycopg2
 && conda install -c conda-forge python-ldap \
 && conda install -c conda-forge psycopg2 \
 && conda install -c conda-forge supervisor \
 # install pangalactic.vger package from my conda repo
 && conda install -c https://pangalactic.us/conda_repo -c conda-forge pangalactic.vger \
 # install postgresql conda package
 && conda install postgresql \
 # remove cached packages etc.
 && conda clean -a \
 # configure postgresql
 && initdb -D /vgerdb \
 && echo "port = 65432" >> /vgerdb/postgresql.conf \
 && pg_ctl -D /vgerdb start \
 && createdb vgerdb

# create the volume *AFTER* all the db commands have finished: any mods to the
# volume after it is declared will be discarded!
VOLUME /vgerdb

# vger.py tries to connect to crossbar at start up
# - location of crossbar can be set using parameters "cb_host" and "cb_port"
#   [default values:  cb_host "localhost", cb_port "8080"]

### "shell form" of ENTRYPOINT
ENTRYPOINT exec /usr/bin/sudo -u scred \
 /home/scred/miniconda/bin/supervisord -c \
 /home/scred/supervisord.conf

